// Generated by dia2code
#ifndef STATE__BUFF__H
#define STATE__BUFF__H

#include <string>

namespace state {

  /// class Buff - 
  class Buff {
    // Attributes
  public:
    std::string nom;
    int nbTurn;
    // Operations
  public:
    Buff ();
    std::string GetName ();
    int GetNbTurn ();
    void SetNbTurn (int );
    // Setters and Getters
  };

};

#endif
