// Generated by dia2code
#ifndef STATE__DEBUFF__H
#define STATE__DEBUFF__H

#include <string>

namespace state {

  /// class Debuff - 
  class Debuff {
    // Attributes
  public:
    std::string name;
    int nbTurn;
    // Operations
  public:
    Debuff ();
    std::string GetName ();
    int GetNbTurn ();
    void SetNbTurn (int );
    // Setters and Getters
  };

};

#endif
