// Generated by dia2code
#ifndef STATE__DISCARDPILE__H
#define STATE__DISCARDPILE__H

#include <memory>

namespace state {
  class Player;
  class DeckParts;
}

#include "Player.h"
#include "DeckParts.h"

namespace state {

  /// class DiscardPile - 
  class DiscardPile : public state::DeckParts {
    // Operations
  public:
    DiscardPile (std::shared_ptr<Player> player);
    // Setters and Getters
  };

};

#endif
