// Generated by dia2code
#ifndef STATE__DISCARDPILE__H
#define STATE__DISCARDPILE__H


namespace state {
  class DeckParts;
}

#include "DeckParts.h"

namespace state {

  /// class DiscardPile - 
  class DiscardPile : public state::DeckParts {
    // Operations
  public:
    DiscardPile ();
    // Setters and Getters
  };

};

#endif
