// Generated by dia2code
#ifndef STATE__DRAWPILE__H
#define STATE__DRAWPILE__H

#include <memory>

namespace state {
  class Player;
  class DeckParts;
}

#include "Player.h"
#include "DeckParts.h"

namespace state {

  /// class DrawPile - 
  class DrawPile : public state::DeckParts {
    // Operations
  public:
    DrawPile (std::shared_ptr<Player> );
    // Setters and Getters
  };

};

#endif
