// Generated by dia2code
#ifndef STATE__ENEMY__H
#define STATE__ENEMY__H

#include <vector>
#include <memory>

namespace state {
  class EnemySkill;
  class Entity;
  class Card;
}

#include "EnemySkill.h"
#include "Entity.h"
#include "Card.h"

namespace state {

  /// class Enemy - 
  class Enemy : public state::Entity {
    // Associations
    // Attributes
  public:
    std::vector<std::shared_ptr<Card>> reward;
    std::vector<std::shared_ptr<EnemySkill>> skills;
    std::shared_ptr<EnemySkill> intent;
    // Operations
  public:
    Enemy ();
    std::vector<std::shared_ptr<EnemySkill>> GetSkills ();
    void SetSkills (std::vector<std::shared_ptr<EnemySkill>> newSkills);
    std::shared_ptr<EnemySkill> GetIntent ();
    void SetIntent (std::shared_ptr<EnemySkill> newIntent);
    // Setters and Getters
  };

};

#endif
