// Generated by dia2code
#ifndef STATE__ENEMYSKILL__H
#define STATE__ENEMYSKILL__H

#include <vector>
#include <memory>
#include <string>

namespace state {
  class Debuff;
  class Buff;
}

#include "Debuff.h"
#include "Buff.h"

namespace state {

  /// class EnemySkill - 
  class EnemySkill {
    // Associations
    // Attributes
  public:
    int attack;
    int block;
    std::vector<std::shared_ptr<Buff>> buffs;
    std::vector<std::shared_ptr<Debuff>> debuffs;
    std::string intentImage;
    int cooldown;
    int turnsBeforeUse;
    // Operations
  public:
    EnemySkill ();
    int GetAttack ();
    void SetAttack (int );
    int GetBlock ();
    void SetBlock (int );
    std::vector<std::shared_ptr<Buff>> GetBuffs ();
    std::vector<std::shared_ptr<Debuff>> GetDebuffs ();
    std::string GetIntentImage ();
    int GetCooldown ();
    int GetTurnsBeforeUse ();
    void SetTurnsBeforeUse (int );
    // Setters and Getters
  };

};

#endif
