// Generated by dia2code
#ifndef STATE__FLOOR__H
#define STATE__FLOOR__H

#include <string>
#include <vector>
#include <memory>

namespace state {
  class Room;
}

#include "Room.h"

namespace state {

  /// class Floor - 
  class Floor {
    // Associations
    // Attributes
  private:
    int nbRoom;
    std::string element;
    std::string floorImage;
    std::vector<std::shared_ptr<Room>> rooms;
    // Operations
  public:
    Floor ();
    std::string GetElement ();
    std::string GetFloorImage ();
    std::vector<std::shared_ptr<Room>> GetRooms ();
    void SetRooms (std::vector<std::shared_ptr<Room>> newRooms);
    // Setters and Getters
  };

};

#endif
