// Generated by dia2code
#ifndef STATE__GAMESTATE__H
#define STATE__GAMESTATE__H

#include <vector>
#include <memory>

namespace state {
  class Map;
  class Rules;
  class Player;
}

#include "Map.h"
#include "Rules.h"
#include "Player.h"

namespace state {

  /// class GameState - 
  class GameState {
    // Associations
    // Attributes
  private:
    std::vector<std::shared_ptr<Player>> players;
    std::shared_ptr<Map> map;
    std::shared_ptr<Rules> rules;
    bool isInsideRoom     = false;
    // Operations
  public:
    GameState ();
    std::vector<std::shared_ptr<Player>> GetPlayers ();
    std::shared_ptr<Map> GetMap ();
    std::shared_ptr<Rules> GetRules ();
    bool GetIsInsideRoom ();
    void SetIsInsideRoom (bool newIsInsideRoom);
    // Setters and Getters
  };

};

#endif
