// Generated by dia2code
#ifndef STATE__HAND__H
#define STATE__HAND__H

#include <memory>

namespace state {
  class Player;
  class DeckParts;
}

#include "Player.h"
#include "DeckParts.h"

namespace state {

  /// class Hand - 
  class Hand : public state::DeckParts {
    // Attributes
  private:
    int sizeMax     = 7;
    // Operations
  public:
    Hand (std::shared_ptr<Player> player);
    int GetSizeMax ();
    // Setters and Getters
  };

};

#endif
