// Generated by dia2code
#ifndef STATE__HAND__H
#define STATE__HAND__H


namespace state {
  class DeckParts;
}

#include "DeckParts.h"

namespace state {

  /// class Hand - 
  class Hand : public state::DeckParts {
    // Attributes
  private:
    int sizeMax     = 7;
    // Operations
  public:
    Hand ();
    int GetSizeMax ();
    // Setters and Getters
  };

};

#endif
