// Generated by dia2code
#ifndef STATE__INITPLAYER__H
#define STATE__INITPLAYER__H

#include <string>

namespace state {

  /// class InitPlayer - 
  class InitPlayer {
    // Attributes
  private:
    std::string BaseElement;
    bool playerControlledByIA     = false;
    // Operations
  public:
    InitPlayer ();
    std::string GetFirstElement ();
    void SetFirstElement (std::string );
    bool GetPlayerControlledByIA ();
    void SetPlayerControlledByIA (bool );
    // Setters and Getters
  };

};

#endif
