// Generated by dia2code
#ifndef STATE__INITPLAYER__H
#define STATE__INITPLAYER__H

#include <string>

namespace state {

  /// class InitPlayer - 
  class InitPlayer {
    // Attributes
  private:
    std::string firstElement;
    bool playerControlledByAI     = false;
    // Operations
  public:
    InitPlayer ();
    std::string GetFirstElement ();
    void SetFirstElement (std::string newFirstElement);
    bool GetPlayerControlledByAI ();
    void SetPlayerControlledByAI (bool newPlayerCBIA);
    // Setters and Getters
  };

};

#endif
