// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <vector>
#include <memory>

namespace state {
  class Floor;
}

#include "Floor.h"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    // Attributes
  private:
    std::vector<std::shared_ptr<Floor>> floors;
    int currentRoom;
    int currentFloor;
    // Operations
  public:
    Map ();
    std::vector<std::shared_ptr<Floor>> GetFloors ();
    int GetCurrentFloor ();
    int GetCurrentRoom ();
    void SetCurrentFloor (int newFloor);
    void SetCurrentRoom (int newRoom);
    // Setters and Getters
  };

};

#endif
