// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <memory>

namespace state {
  class Deck;
  class Entity;
}

#include "Deck.h"
#include "Entity.h"

namespace state {

  /// class Player - 
  class Player : public state::Entity {
    // Associations
    // Attributes
  public:
    int energy;
    std::shared_ptr<Deck> deck;
    // Operations
  public:
    Player ();
    // Setters and Getters
  };

};

#endif
