// Generated by dia2code
#ifndef STATE__ROOM__H
#define STATE__ROOM__H

#include <string>

namespace state {

  /// class Room - 
  class Room {
    // Attributes
  private:
    int roomNumber;
    std::string element;
    std::string imageMapRoom;
    std::string imageInsideRoom;
    bool isSpecialTrainingRoom;
    bool isEnemyRoom;
    bool isSleepRoom;
    // Operations
  public:
    Room ();
    Room (int roomNb, std::string elem, bool isSTR, bool isER, bool isSR);
    std::string GetImageMapRoom ();
    std::string GetImageInsideRoom ();
    bool GetIsSpecialTrainingRoom ();
    bool GetIsEnemyRoom ();
    bool GetIsSleepRoom ();
    std::string GetElement ();
    // Setters and Getters
  };

};

#endif
