// Generated by dia2code
#ifndef STATE__RULES__H
#define STATE__RULES__H

#include <vector>
#include <memory>

namespace state {
  class InitPlayer;
}

#include "InitPlayer.h"

namespace state {

  /// class Rules - 
  class Rules {
    // Associations
    // Attributes
  private:
    bool isGameLost;
    bool isGameOver;
    int nbPlayers;
    std::vector<std::shared_ptr<InitPlayer>> initPlayer;
    // Operations
  public:
    Rules ();
    bool GetIsGameLost ();
    bool GetIsGameOver ();
    void SetIsGameLost (bool newIsGamesLost);
    void SetIsGameOver (bool newIsGameOver);
    int GetNbPlayers ();
    void SetNbPlayers (int newNbPlayers);
    std::vector<std::shared_ptr<InitPlayer>> GetInitPlayer ();
    void SetInitPlayer (std::vector<std::shared_ptr<InitPlayer>> newInitPlayer);
    // Setters and Getters
  };

};

#endif
