// Generated by dia2code
#ifndef STATE__RULES__H
#define STATE__RULES__H

#include <vector>
#include <memory>

namespace state {
  class InitPlayer;
}

#include "InitPlayer.h"

namespace state {

  /// class Rules - 
  class Rules {
    // Associations
    // Attributes
  private:
    bool IsGameLost;
    bool IsGameOver;
    int nbPlayers;
    std::vector<std::shared_ptr<InitPlayer>> initPlayer;
    // Operations
  public:
    Rules ();
    bool GetIsGameLost ();
    bool GetIsGameOver ();
    void SetIsGameLost (bool );
    void SetIsGameOver (bool );
    int GetNbPlayers ();
    void SetNbPlayers (int );
    InitPlayer GetInitPlayer ();
    void SetInitPlayer (InitPlayer );
    // Setters and Getters
  };

};

#endif
