// Generated by dia2code
#ifndef STATE__SPECIALTRAININGROOM__H
#define STATE__SPECIALTRAININGROOM__H

#include <vector>
#include <memory>
#include <string>

namespace state {
  class Card;
  class Room;
}

#include "Card.h"
#include "Room.h"

namespace state {

  /// class SpecialTrainingRoom - 
  class SpecialTrainingRoom : public state::Room {
    // Attributes
  private:
    std::vector<std::shared_ptr<Card>> cardReward;
    // Operations
  public:
    SpecialTrainingRoom ();
    SpecialTrainingRoom (int roomNumber, std::string element, std::vector<std::shared_ptr<Card>> cardReward);
    std::vector<std::shared_ptr<Card>> GetCardReward ();
    // Setters and Getters
  };

};

#endif
