// Generated by dia2code
#ifndef RENDER__EDITEUR__H
#define RENDER__EDITEUR__H

#include <SFML/Graphics.hpp>
#include <memory>

namespace state {
  class Card;
}

#include "state/Card.h"

namespace render {

  /// class Editeur - 
  class Editeur {
    // Associations
    // Attributes
  private:
    int x;
    int y;
    int width;
    int height;
    sf::RenderTexture  texture;
    // Operations
  public:
    Editeur ();
    ~Editeur ();
    Editeur (int x, int y, int width, int height, std::shared_ptr<state::Card>& card);
    void Click (int x, int y);
    int const GetX ();
    int const GetY ();
    int const GetWidth ();
    int const GetHeight ();
    sf::RenderTexture& GetTexture ();
    // Setters and Getters
  };

};

#endif
