// Generated by dia2code
#ifndef RENDER__LOADTEXTURES__H
#define RENDER__LOADTEXTURES__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace render {

  /// class LoadTextures - 
  class LoadTextures {
    // Attributes
  public:
    sf::Texture texturePile;
    std::vector<sf::Texture> textureCard;
    std::vector<sf::Texture> textureIcon;
    std::vector<sf::Texture> texturePlayer;
    std::vector<sf::Texture> textureEnemy;
    std::vector<sf::Texture> textureElement;
    std::vector<sf::Texture> textureBackGround;
    sf::Texture textureButton;
    std::vector<sf::Texture> textureMapBackground;
    std::vector<sf::Texture> textureMapIcon;
    // Operations
  public:
    LoadTextures ();
    ~LoadTextures ();
    // Setters and Getters
  };

};

#endif
