// Generated by dia2code
#ifndef RENDER__LOADTEXTURES__H
#define RENDER__LOADTEXTURES__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace render {

  /// class LoadTextures - 
  class LoadTextures {
    // Attributes
  public:
    sf::Sprite TexturePile;
    std::vector<sf::Sprite> TextureCard;
    std::vector<sf::Sprite> TextureIcon;
    std::vector<sf::Sprite> TexturePlayer;
    std::vector<sf::Sprite> TextureEnemy;
    std::vector<sf::Sprite> TextureElement;
    std::vector<sf::Sprite> TextureBackGround;
    sf::Sprite TextureButton;
    std::vector<sf::Sprite> TextureMapBackground;
    std::vector<sf::Sprite> TextureMapIcon;
    // Operations
  public:
    LoadTextures ();
    ~LoadTextures ();
    // Setters and Getters
  };

};

#endif
