// Generated by dia2code
#ifndef RENDER__VIEW__H
#define RENDER__VIEW__H

#include <memory>
#include <SFML/Graphics.hpp>

namespace render {
  class Rendu;
};
namespace state {
  class GameState;
}

#include "Rendu.h"
#include "state/GameState.h"

namespace render {

  /// class View - 
  class View {
    // Associations
    // Attributes
  private:
    std::unique_ptr<Rendu> rendu;
    std::shared_ptr<state::GameState> gameState;
    std::unique_ptr<sf::RenderWindow> window;
    // Operations
  public:
    View ();
    View (std::shared_ptr<state::GameState>& gameState);
    ~View ();
    std::unique_ptr<Rendu>& GetRendu ();
    std::shared_ptr<state::GameState>& GetGameState ();
    std::unique_ptr<sf::RenderWindow>& GetWindow ();
    void Draw ();
    // Setters and Getters
  };

};

#endif
